name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "$" > "$HOME/.ssh/ifvfkj1997"
      - run: chmod 600 "$HOME/.ssh/ifvfkj1997"
      # Build
      - run: npm ci
      - run: npm run build
      # Deploy
      - run: cd app && rsync -e "ssh -p 20022 -i $HOME/.ssh/ifvfkj1997 -o StrictHostKeyChecking=no" --archive  --compress --delete . m71516@hostru04.fornex.org:/home/git@github.com:gymmish/goit-markup-hw-02.git
